# This workflow runs a CI test to ensure your documentation still builds.

name: "Pull Request Docs Check"
on: 
  pull_request:
    branches:
      - main
    paths:
      - docs/**
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.2.0
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install/Update  build dependencies
        run: |
          python -m pip install --upgrade setuptools
          python -m pip install --upgrade pip
      - name: Install Poetry
        run: |
          curl -sL https://install.python-poetry.org | python -
      - name: Update Pip
        run: poetry run pip install -U pip setuptools
      - name: Install Dependencies
        run: poetry install
      - uses: pre-commit/action@v3.0.0

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Update pip
      run: |
        pip install -U wheel
        pip install -U setuptools
        python -m pip install -U pip
    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
    - name: Pip cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Sphinx-PDF Generated Package
      run: |
        pip install -e .
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        build-command: "sphinx-pdf-generate -b html . _build/html"

  linkcheck:
    name: Docs-Linkcheck
    runs-on: ubuntu-20.04
    env:
      ON_CI: true
    steps:
      - uses: actions/checkout@v3.2.0
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Nox Dependencies
        run: |
          python -m pip install poetry nox nox-poetry pyparsing==3.0.4
      - name: Run LinkCheck
        run: nox --non-interactive --session linkcheck -- --full-trace